import os
from twilio.rest import Client
import time
from datetime import datetime as dt

account_sid = os.environ['TWILIO_ACCOUNT_SID'] # from account
auth_token = os.environ['TWILIO_AUTH_TOKEN']
client = Client(account_sid, auth_token)

while True:
  now = dt.now()
  if now.hour == 13 and now.minute == 15: #every day at 13:15
    message = client.messages \
                    .create(
                        body="Test test test",
                        from_='+1000', #number generated by twilio
                        to='+20' # your verified number
                    )

    print(message.sid) #sid -> unique ID message
  time.sleep(60) # checks every 60 seconds
